config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :posts do
    resources :comments, only: [:create]
  end
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
  get 'friends/list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
class Friend < ApplicationRecord

    belongs_to :user
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "You are not Authorized" if @friend.nil?
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:user_id, :first_name, :last_name, :email, :phone, :twitter, :avater)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-3">
    <%= form.text_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter user name" %>
  </div>

  <div class="field form-group mb-3">
    <%= form.label :avatar %>
    <%= form.file_field :avatar , class:"form-control", placeholder:"Choose profile Image" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<div class="container"> 
    <h1>Editing Friend</h1>

    <%= render 'form', friend: @friend %>
    <br/>
    <%= link_to 'Show', @friend, class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark" %>
    <%= link_to 'Back', friends_path, class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark" %>
</div>

app/views/friends/index.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-12">
      <div class="card mb-4">
        <div class="card-header pb-0 d-flex">
          <h6 class="me-10">Friends table</h6>
          <%= link_to '', new_friend_path, class:"btn btn-secondary btn-round btn-sm fas fa-plus" %>
        </div>
        <div class="card-body px-0 pt-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">User Name</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Phone</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Twitter</th>
                  <th class="text-secondary opacity-7">Action</th>
                </tr>
              </thead>
              <tbody>
                <% @friends.each do |friend| %>
                  <% if friend.user == current_user %>
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div>
                            <%# <%= image_tag(friend.avatar, class:"avatar avatar-sm me-3") %>
                          </div>
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">
                            <%= friend.first_name %> &nbsp <%= friend.last_name %> </h6>
                            <p class="text-xs text-secondary mb-0"><%= friend.email %></p>
                          </div>
                        </div>
                      </td>
                      <td>
                        <p class="text-xs text-secondary mb-0"><%= friend.phone %></p>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <p class="text-xs text-secondary mb-0"><%= friend.twitter %></p>
                      </td>
                      <td class="align-middle">
                        <%= link_to '', friend, class:"fas fa-eye me-2" %>
                        <%= link_to '', edit_friend_path(friend), class:"fas fa-edit me-2" %>
                        <%= link_to '', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"fas fa-trash" %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/friends/new.html.erb
<div class="container">
    <h1>Add New Friend</h1>
    <%= render 'form', friend: @friend %>
    <br/>
    <%= link_to 'Back', friends_path, class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="container">
  <div class="h-100 p-5 bg-light border rounded-3">
    <h5 class="display-5"><%= @friend.first_name %><%= @friend.last_name %></h5>
    <p class="lead"><%= @friend.email %></p>
    <p class="lead"><%= @friend.phone %></p>
    <p class="lead"><%= @friend.twitter %></p>
    <br/>
    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark" %>
    <%= link_to 'Back', friends_path, class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark" %>
  </div>

</div>