config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :posts do
    resources :comments, only: [:create]
  end
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
  get 'friends/list'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end
  
  def about
  	
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="footer py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mb-4 mx-auto text-center">
        <%= link_to 'dongoFriends', root_path, class:"text-secondary me-xl-5 me-3 mb-sm-0 mb-2 footer-link" %>
        <%= link_to 'Posts', posts_path, class:"text-secondary me-xl-5 me-3 mb-sm-0 mb-2 footer-link" %>
        <%= link_to 'Friends', friends_path, class:"text-secondary me-xl-5 me-3 mb-sm-0 mb-2 footer-link" %>
      </div>
    </div>
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          Copyright © 2021 Dongo.
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-9 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
          <%= link_to 'dongoFriends', root_path, class:"navbar-brand font-weight-bolder ms-lg-0 ms-3" %>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse" id="navigation">
              <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                  <%= link_to 'Home', root_path, class:"nav-link me-2" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Posts', posts_path, class:"nav-link me-2" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Friends', friends_path, class:"nav-link me-2" %>
                </li>
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to 'Add Friends', new_friend_path, class:"nav-link me-2" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link me-2" %>
                  </li>
                  <ul class="navbar-nav d-lg-block d-none">
                    <li class="nav-item">
                      <%= link_to image_tag(current_user.avatar_thumbnail, class:"profile me-1") + '', edit_user_registration_path %>
                    </li>
                  </ul>
                <%end%>
              </ul>
              <% if !user_signed_in? %>
                <ul class="navbar-nav d-lg-block d-none">
                  <li class="nav-item">
                    <%= link_to 'Login', new_user_session_path, class:"btn btn-sm btn-round mb-0 me-1 bg-gradient-dark" %>
                  </li>
                </ul>
              <%end%>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

app/views/home/about.html.erb
<h2>About page ...</h2>

app/views/home/index.html.erb
<div class="container">
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "f15.jpg", class:"img-fluid" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "f16.jpg", class:"img-fluid" %>
      </div>
      <div class="carousel-item">
        <%= image_tag "f13.jpg", class:"img-fluid" %>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="services">
    <div class="row mt-4 pt-4">
      <div class="col-md-4 col-sm-6">
        <div class="card" style="width: 18rem;">
          <div class="message_icons"><%= image_tag "message.png", class:"img-fluid" %></span></div>
          <div class="card-body">
            <h5 class="card-title">Messaging</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="card" style="width: 18rem;">
          <div class="support_icons"><%= image_tag "support.png", class:"img-fluid" %></span></div>
          <div class="card-body">
            <h5 class="card-title">Support</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-sm-6">
        <div class="card" style="width: 18rem;">
          <div class="management_icons"><%= image_tag "management.png", class:"img-fluid" %></span></div>
          <div class="card-body">
            <h5 class="card-title">Management</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="posts">
    <div class="row">
      <div class="col-12">
        <h3>Latest Posts</h3>
      </div>
    </div>

    <div class="row">
      <% @posts.each do |post| %>
        <div class="col-lg-6 col-md-6 col-sm-12">
          <div class="card mb-3" style="max-width: 580px;">
            <div class="row g-0">
              <div class="col-md-6">
                <%= link_to image_tag(post.thumbnail, class:"img-fluid") + '', post %>
              </div>
              <div class="col-md-6">
                <div class="card-body">
                  <h5 class="card-title"><%= link_to post.title.truncate_words(5) + '', post %></h5>
                  <p class="card-text"><%= post.body.to_plain_text.truncate_words(10) %></p>
                  <div class="post_user">
                    <%= image_tag "default_profile.jpg", class:"img-fluid" %>
                    <span><%= post.user.email %></span>
                  </div>
                  <small class="text-muted"><%= post.updated_at.strftime("%A %B %Y") %> | <%= pluralize(post.views, "View") %></small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="subscribers">
    <h3>Subscrib Now</h3>
    <p>For the latest posts and news subscrib today</p>
  </div>
</div>